@url=http://localhost:5000
@contentType = application/json


### home
GET {{url}}

### get account
GET {{url}}/account/1

### create account
POST {{url}}/account 

{
  "holder":"holder 005",
  "balance":15
}

### get account list

GET {{url}}/account?pageLimit=10

### get account list from last id
GET {{url}}/account?lastId=1200&pageLimit=10



### custome validation
### bookabledate
POST {{url}}/validation

{
  "checkIn":"2023-02-23T00:00:00Z",
  "checkOut":"2023-02-22T00:00:00Z"
}
 
### default form
GET {{url}}/validation/defaultForm?name=jack

### bookabledate
POST {{url}}/validation/defaultJson

{
  "name":"jimbo"
}


### token get token
GET {{url}}/token


### token get decryption
POST {{url}}/token

{
  "enc":"jvgqa_fdMiYTMXVQI6imrPaEgHt2LNmcmIYnMvvJHG9PO_nIpmaT8x0jKT2kEReQjURWLcLSsTM8mMPpSL-4fs1VhBH4am2wUfOxzw5Cxl0BUTPF4PgKcxmUi2i1J72B7BjSeqza140mO9yzHfenY7tXyQ-RYXUEx2HGtYViVojNM1eiU2A0oDqyFTMDUjcJ0_erqwA3QN_RUGvkBSc"
}