// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: entry.sql

package sqlc

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entry (
  account_id ,
  amount,
  note
) VALUES (
  $1, $2, $3
)
RETURNING id, account_id, amount, note
`

type CreateEntryParams struct {
	AccountID int64  `json:"account_id"`
	Amount    int64  `json:"amount"`
	Note      string `json:"note"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountID, arg.Amount, arg.Note)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Note,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, account_id, amount, note FROM entry
where id=$1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Note,
	)
	return i, err
}

const getEntryList = `-- name: GetEntryList :many
SELECT ac.id,ac.holder,ac.balance,
en.amount,en.note
FROM "account" as ac 
INNER JOIN "entry" as en
on ac.id = en."account_id"
where ac.id = $1::bigint
and en.id > $2::bigint
limit $3
`

type GetEntryListParams struct {
	AccountID   int64 `json:"account_id"`
	EntryLastID int64 `json:"entry_last_id"`
	PageSize    int32 `json:"page_size"`
}

type GetEntryListRow struct {
	ID      int64  `json:"id"`
	Holder  string `json:"holder"`
	Balance int64  `json:"balance"`
	Amount  int64  `json:"amount"`
	Note    string `json:"note"`
}

func (q *Queries) GetEntryList(ctx context.Context, arg GetEntryListParams) ([]GetEntryListRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntryList, arg.AccountID, arg.EntryLastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntryListRow{}
	for rows.Next() {
		var i GetEntryListRow
		if err := rows.Scan(
			&i.ID,
			&i.Holder,
			&i.Balance,
			&i.Amount,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
