// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import ()

type Account struct {
	ID      int64  `json:"id"`
	Holder  string `json:"holder"`
	Balance int64  `json:"balance"`
}

type Entry struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"account_id"`
	Amount    int64  `json:"amount"`
	Note      string `json:"note"`
}

type Tbempty struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
