// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountList(ctx context.Context, arg GetAccountListParams) ([]Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetEntryList(ctx context.Context, arg GetEntryListParams) ([]GetEntryListRow, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
